server/e-commerce/src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private $specification = [];

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $html_description;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $stock;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $numberClick;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_At;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="articles")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Categorie", inversedBy="articles")
     */
    private $categorie;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $solde;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getSpecification(): ?array
    {
        return $this->specification;
    }

    public function setSpecification(?array $specification): self
    {
        $this->specification = $specification;

        return $this;
    }

    public function getHtmlDescription(): ?string
    {
        return $this->html_description;
    }

    public function setHtmlDescription(?string $html_description): self
    {
        $this->html_description = $html_description;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(?int $stock): self
    {
        $this->stock = $stock;

        return $this;
    }

    public function getNumberClick(): ?int
    {
        return $this->numberClick;
    }

    public function setNumberClick(?int $numberClick): self
    {
        $this->numberClick = $numberClick;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_At;
    }

    public function setCreatedAt(\DateTimeInterface $created_At): self
    {
        $this->created_At = $created_At;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getSolde(): ?int
    {
        return $this->solde;
    }

    public function setSolde(?int $solde): self
    {
        $this->solde = $solde;

        return $this;
    }

}

server/e-commerce/src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('description')
            ->add('title')
            ->add('price')
            ->add('specification')
            ->add('html_description')
            ->add('stock')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

server/e-commerce/src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\Picture;
use App\Entity\Categorie;
use App\Form\ArticleType;
use App\Repository\ArticleRepository;
use App\Repository\PictureRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Serializer\Serializer;
use App\Repository\CategorieRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Encoder\XmlEncoder;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


/**
 * @Route("/article")
 */
class ArticleController extends AbstractController
{

    /**
     * Find Article by Categories
     * @Route("/categorie/{categorie_id}", name="article_by_category", methods={"GET"})
     */
    public function findFilter($categorie_id, ArticleRepository $categorieRepository):Response
    {
        $encoders = [new XmlEncoder(), new JsonEncoder()];
        $normalizers = [new ObjectNormalizer()];
        $serializer = new Serializer($normalizers, $encoders);
        $articles = $categorieRepository->findByCategorie($categorie_id);
        $jsonContent = $serializer->serialize($articles, 'json', [
            'circular_reference_handler' => function ($object) {
                return $object->getId();
            }
        ]);
        $article = new Response($jsonContent);
        $article->headers->set('Content-Type', 'application-json');
        $article->headers->set('Access-Control-Allow-Origin', '*');
        $article->headers->set('Access-Control-Allow-Methods', 'POST, GET, PUT, OPTIONS');
        return $article;
    }

    /**
     * Fetch All Articles
     * @Route("/", name="article_index", methods={"GET"})
     */
    public function index(ArticleRepository $articleRepository): Response
    {
        $encoders = [new XmlEncoder(), new JsonEncoder()];
        $normalizers = [new ObjectNormalizer()];
        $serializer = new Serializer($normalizers, $encoders);
        $all_articles = $articleRepository->findBy(array(), array('numberClick' => 'desc') );;
        $jsonContent = $serializer->serialize($all_articles, 'json', [
            'circular_reference_handler' => function ($object) {
                return $object->getId();
            }
        ]);
        $articles = new Response($jsonContent);
        $articles->headers->set('Content-Type', 'application-json');
        $articles->headers->set('Access-Control-Allow-Origin', '*');
        $articles->headers->set('Access-Control-Allow-Methods', 'GET, OPTIONS');
        return $articles;
    }

    /**
     * @Route("/new", name="article_new", methods={"GET","POST"})
     */
    public function new(Request $request, UserRepository $userRepository, CategorieRepository $categorieRepository): Response
    {
      $token = $request->headers->get('Authorization');
      if (in_array("ROLE_ADMIN", $userRepository->isAuth($token)->role)) {
        $article = new Article();
        $article->setTitle($request->request->get('title'));
        $article->setDescription($request->request->get('description'));
        $article->setPrice($request->request->get('price'));
        $article->setCreatedAt(new \DateTime());
        $article->setSpecification(json_decode($request->request->get('specifications')));
        $article->setStock($request->request->get('stock'));

        $cat = $categorieRepository->findCategory($request->request->get('categorie'));
        $em = $this->getDoctrine()->getManager();
        if($cat != []) {
          $categorie = $this->getDoctrine()->getRepository(Categorie::class)->find($cat[0]['id']);
        } else {
          $categorie = new Categorie();
          $categorie->setCategorie($request->request->get('categorie'));
          $article->setCategorie($categorie);
          $em->persist($categorie);
        }
        $article->setCategorie($categorie);

        $pictureFile = [];
        $i = 0;
        while ($request->files->get('pic' . $i) != '') {
          $pictureFile[] = $request->files->get('pic' . $i);
          $i++;
        }
        for ($j = 0; $j < count($pictureFile); $j++) {
          $originalFilename = pathinfo($pictureFile[$j]->getClientOriginalName(), PATHINFO_FILENAME);
          $safeFilename = transliterator_transliterate('Any-Latin; Latin-ASCII; [^A-Za-z0-9_] remove; Lower()', $originalFilename);
          $newFilename = $safeFilename . '-' . uniqid() . '.' . $pictureFile[$j]->guessExtension();
          try {
            $pictureFile[$j]->move('image/article', $newFilename);
          } catch (FileExeption $e) {
            $msg = ['success' => $e];
          }
          $picture = new Picture();
          $picture->setArticleId($article);
          $picture->setPath($newFilename);
          $em->persist($picture);
        }
        $em->persist($article);

        if ($em->flush() == null) $msg = ['success' => 'Article Saved'];
        else $msg = ['success' => 'An error occured'];
      } else {
        $msg = ['error' => 'An error occured'];
      }

      $ret = new Response(json_encode($msg));
      $ret->headers->set('Content-Type', 'application/json');
      $ret->headers->set('Access-Control-Allow-Origin', '*');
      $ret->headers->set('Access-Control-Allow-Methods', 'POST, GET, PUT, OPTIONS');
      return $ret;
    }

    /**
     * Find Article by Id (Article's details)
     * @Route("/{id}", name="article_show", methods={"GET"})
     */
    public function show($id, Article $article, ArticleRepository $articleRepository): Response
    {

        $encoders = [new XmlEncoder(), new JsonEncoder()];
        $normalizers = [new ObjectNormalizer()];
        $serializer = new Serializer($normalizers, $encoders);
        $article = $articleRepository->find($id);
        $jsonContent = $serializer->serialize($article, 'json', [
            'circular_reference_handler' => function ($object) {
                return $object->getId();
            }
        ]);
        $article = new Response($jsonContent);
        $article->headers->set('Content-Type', 'application-json');
        $article->headers->set('Access-Control-Allow-Origin', '*');
        $article->headers->set('Access-Control-Allow-Methods', 'GET, OPTIONS');
        return $article;
    }

    /**
     * @Route("/picture/{id}", name="article_picture", methods={"GET"})
     */
    public function getPicture($id, Article $article, PictureRepository $pictureRepository): Response
    {
        $encoders = [new XmlEncoder(), new JsonEncoder()];
        $normalizers = [new ObjectNormalizer()];
        $serializer = new Serializer($normalizers, $encoders);
        $all_picture = $pictureRepository->findByArticleId($id);
        $jsonContent = $serializer->serialize($all_picture, 'json', [
            'circular_reference_handler' => function ($object) {
                return $object->getId();
            }
        ]);

        $picture = new Response($jsonContent);
        $picture->headers->set('Content-Type', 'application-json');
        $picture->headers->set('Access-Control-Allow-Origin', '*');
        $picture->headers->set('Access-Control-Allow-Methods', 'POST, GET, PUT, OPTIONS');
        return $picture;
    }

    /**
     * @Route("/{id}/edit", name="article_edit", methods={"GET", "POST"})
     */
    public function edit($id, Request $request, ArticleRepository $articleRepository, Article $article, UserRepository $userRepository): Response
    {        
        $token = $request->headers->get('Authorization');
        
        if (in_array("ROLE_ADMIN", $userRepository->isAuth($token)->role)) {
        
            $article->setTitle($request->request->get('title'));
            $article->setDescription($request->request->get('description'));
            $article->setPrice($request->request->get('price'));
            $article->setSolde($request->request->get('solde'));
            $article->setStock($request->request->get('stock'));
            $article->setCreatedAt(new \DateTime());
            $article->setSpecification(json_decode($request->request->get('specifications')));                        
            
            $em = $this->getDoctrine()->getManager();

            $pictureFile = [];
            $i = 0;
            while ($request->files->get('pic' . $i) != '') {
                $pictureFile[] = $request->files->get('pic' . $i);
                $i++;
            }
            for ($j = 0; $j < count($pictureFile); $j++) {
                $originalFilename = pathinfo($pictureFile[$j]->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = transliterator_transliterate('Any-Latin; Latin-ASCII; [^A-Za-z0-9_] remove; Lower()', $originalFilename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $pictureFile[$j]->guessExtension();
                try {
                    $pictureFile[$j]->move('image/article', $newFilename);
                } catch (FileExeption $e) {
                    $msg = ['success' => $e];
                }
                $picture = new Picture();
                $picture->setArticleId($article);
                $picture->setPath($newFilename);
                $em->persist($picture);
            }
        
            $em->persist($article);

            if ($em->flush() == null) $msg = ['success' => 'Article updated successfuly'];
            else $msg = ['success' => 'Sorry, some error occured'];
        
        }else{
            $msg = ['error' => 'Action Denied! Bad Credentials :('];
        }
        $ret = new Response(json_encode($msg));
        $ret->headers->set('Content-Type', 'application/json');
        $ret->headers->set('Access-Control-Allow-Origin', '*');
        $ret->headers->set('Access-Control-Allow-Methods', 'POST, GET, PUT, OPTIONS');
        return $ret;        
    }

server/e-commerce/templates/article/_delete_form.html.twig
<form method="post" action="{{ path('article_delete', {'id': article.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <button class="btn">Delete</button>
</form>

server/e-commerce/templates/article/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

server/e-commerce/templates/article/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Article{% endblock %}

{% block body %}
    <h1>Edit Article</h1>

    {{ include('article/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('article_index') }}">back to list</a>

    {{ include('article/_delete_form.html.twig') }}
{% endblock %}

server/e-commerce/templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article index{% endblock %}

{% block body %}
    <h1>Article index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Description</th>
                <th>Title</th>
                <th>Price</th>
                <th>Specification</th>
                <th>Html_description</th>
                <th>Stock</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for article in articles %}
            <tr>
                <td>{{ article.id }}</td>
                <td>{{ article.description }}</td>
                <td>{{ article.title }}</td>
                <td>{{ article.price }}</td>
                <td>{{ article.specification ? article.specification|json_encode : '' }}</td>
                <td>{{ article.htmlDescription }}</td>
                <td>{{ article.stock }}</td>
                <td>
                    <a href="{{ path('article_show', {'id': article.id}) }}">show</a>
                    <a href="{{ path('article_edit', {'id': article.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('article_new') }}">Create new</a>
{% endblock %}

server/e-commerce/templates/article/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Article{% endblock %}

{% block body %}
    <h1>Create new Article</h1>

    {{ include('article/_form.html.twig') }}

    <a href="{{ path('article_index') }}">back to list</a>
{% endblock %}

server/e-commerce/templates/article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article{% endblock %}

{% block body %}
    <h1>Article</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ article.id }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ article.description }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ article.title }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ article.price }}</td>
            </tr>
            <tr>
                <th>Specification</th>
                <td>{{ article.specification ? article.specification|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Html_description</th>
                <td>{{ article.htmlDescription }}</td>
            </tr>
            <tr>
                <th>Stock</th>
                <td>{{ article.stock }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('article_index') }}">back to list</a>

    <a href="{{ path('article_edit', {'id': article.id}) }}">edit</a>

    {{ include('article/_delete_form.html.twig') }}
{% endblock %}