server/e-commerce/src/Entity/User.php
<?php

namespace App\Entity;

use Serializable;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;


    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_online;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $phone;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Adresse", mappedBy="user_id")
     */
    private $adresses;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Article", mappedBy="user")
     */
    private $articles;

    public function __construct()
    {
        $this->adresses = new ArrayCollection();
        $this->articles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles()
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getIsOnline(): ?bool
    {
        return $this->is_online;
    }

    public function setIsOnline(bool $is_online): self
    {
        $this->is_online = $is_online;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * @return Collection|Adresse[]
     */
    public function getAdresses(): Collection
    {
        return $this->adresses;
    }

    public function addAdress(Adresse $adress): self
    {
        if (!$this->adresses->contains($adress)) {
            $this->adresses[] = $adress;
            $adress->setUserId($this);
        }

        return $this;
    }

    public function removeAdress(Adresse $adress): self
    {
        if ($this->adresses->contains($adress)) {
            $this->adresses->removeElement($adress);
            // set the owning side to null (unless already changed)
            if ($adress->getUserId() === $this) {
                $adress->setUserId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Article[]
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): self
    {
        if (!$this->articles->contains($article)) {
            $this->articles[] = $article;
            $article->setUser($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): self
    {
        if ($this->articles->contains($article)) {
            $this->articles->removeElement($article);
            // set the owning side to null (unless already changed)
            if ($article->getUser() === $this) {
                $article->setUser(null);
            }
        }

        return $this;
    }
}

server/e-commerce/src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email')
            ->add('password')
            ->add('lastname')
            ->add('firstname')
            ->add('phone')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

server/e-commerce/src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use App\Repository\AdresseRepository;
use App\Repository\CreditCardRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use App\Entity\Adresse;
use App\Entity\CreditCard;
use Symfony\Component\Serializer\Serializer;
use Symfony\Component\Serializer\Encoder\XmlEncoder;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
/**
 * @Route("/user")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/", name="user_index", methods={"GET"})
     */
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="user_new", methods={"GET","POST"})
     */
    public function new(Request $request,UserPasswordEncoderInterface $encoder): Response
    {

        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $plainPassword = $user->getPassword();
            $encoded = $encoder->encodePassword($user, $plainPassword);

            $user->setRoles(['ROLE_USER']);
            $user->setIsOnline(false);
            $user->setPassword($encoded);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('user_index');
        }
        return $this->render('user/new.html.twig', [
            'user' => $user,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/{id}", name="user_show", methods={"GET"})
     */
    public function show(User $user): Response
    {
        $ret = new Response(json_encode(
            [
                "email" => $user->getEmail(),
                "firstname" => $user->getFirstname(),
                "lastname" => $user->getLastname(),
                "phone" => $user->getPhone()
            ]
        ));
        $ret->headers->set('Content-Type', 'application-json');
        $ret->headers->set('Access-Control-Allow-Origin', '*');
        $ret->headers->set('Access-Control-Allow-Methods', 'POST, GET, PUT, OPTIONS');

        return $ret;
    }

    /**
     * @Route("/{id}/edit", name="user_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, User $user, UserPasswordEncoderInterface $encoder): Response
    {

        $user_data = json_decode($request->getContent(), true);

        $user->setFirstname($user_data['firstname']);
        $user->setLastname($user_data['lastname']);
        $user->setEmail($user_data['email']);
        $user->setPhone($user_data['phone']);

        $em = $this->getDoctrine()->getManager();
        $em->persist($user);

        $em->flush();

        $msg = ['success' => 'Article Saved'];
        $ret = new Response(json_encode($msg));
        $ret->headers->set('Content-Type', 'application/json');
        $ret->headers->set('Access-Control-Allow-Origin', '*');
        $ret->headers->set('Access-Control-Allow-Methods', 'POST, GET, PUT, OPTIONS');
        return $ret;
    }

    /**
     * @Route("/{id}", name="user_delete", methods={"DELETE"})
     */
    public function delete(Request $request, User $user): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
        }

        $msg = ['success' => 'User deleted'];
        $ret = new Response(json_encode($msg));
        $ret->headers->set('Content-Type', 'application/json');
        $ret->headers->set('Access-Control-Allow-Origin', '*');
        $ret->headers->set('Access-Control-Allow-Methods', 'POST, GET, PUT, OPTIONS');
        return $ret;
    }

    /**
     * @Route("/{id}/adress", name="user_adress", methods={"POST"})
     */
    public function userAdress($id, Request $request, UserRepository $userRepository): Response
    {
        $adresse = new Adresse;
        $user = $userRepository->find($id);

        $adresse->setUserId($user);
        $adresse->setAdresse($request->request->get('adress'));
        $adresse->setCity($request->request->get('city'));
        $adresse->setPostCode($request->request->get('postcode'));
        $adresse->setContry($request->request->get('country'));

        $em = $this->getDoctrine()->getManager();
        $em->persist($adresse);

        $em->flush();

        $msg = ['success' => 'Adresse Saved'];
        $ret = new Response(json_encode($msg));
        // $ret = new Response(json_encode($request->request->get('city')));
        $ret->headers->set('Content-Type', 'application/json');
        $ret->headers->set('Access-Control-Allow-Origin', '*');
        $ret->headers->set('Access-Control-Allow-Methods', 'POST, GET, PUT, OPTIONS');
        return $ret;
    }

    /**
     * @Route("/{id}/card", name="user_card", methods={"POST"})
     */
    public function userCard($id, Request $request, UserRepository $userRepository): Response
    {
        $card = new CreditCard;
        $user = $userRepository->find($id);

        $date = new \DateTime($request->request->get('expiration'));

        $card->setUserId($user);
        $card->setCardNumber($request->request->get('card'));
        $card->setExpirationDate($date);


        $em = $this->getDoctrine()->getManager();
        $em->persist($card);
        $em->flush();

        $msg = ['success' => 'Card Saved'];
        $ret = new Response(json_encode($msg));

        $ret->headers->set('Content-Type', 'application/json');
        $ret->headers->set('Access-Control-Allow-Origin', '*');
        $ret->headers->set('Access-Control-Allow-Methods', 'POST, GET, PUT, OPTIONS');
        return $ret;
    }

    /**
     * @Route("/{id}/getAdresse", name="user_getAdress", methods={"GET"})
     */
    public function getAdress($id, AdresseRepository $adresseRepository): Response
    {
        $encoders = [new XmlEncoder(), new JsonEncoder()];
        $normalizers = [new ObjectNormalizer()];
        $serializer = new Serializer($normalizers, $encoders);

        $adresse = $adresseRepository->findByUserId($id);

        $jsonContent = $serializer->serialize($adresse, 'json', [
            'circular_reference_handler' => function ($object) {
                return $object->getId();
            }
        ]);

        // dd($adresse);

        $ret = new Response($jsonContent);
        $ret->headers->set('Content-Type', 'application/json');
        $ret->headers->set('Access-Control-Allow-Origin', '*');
        $ret->headers->set('Access-Control-Allow-Methods', 'POST, GET, PUT, OPTIONS');
        return $ret;
    }

    /**
     * @Route("/delete/adresse/{id}", name="user_deleteAdresse", methods={"DELETE"})
     */
    public function deleteAdresse(Request $request, AdresseRepository $adresseRepository, UserRepository $userRepository, Adresse $adresse): Response
    {
        $token = $request->headers->get('Authorization');
        if (in_array("ROLE_USER", $userRepository->isAuth($token)->role)){

            $adresse = $adresseRepository->find($adresse->getId());
            $em = $this->getDoctrine()->getManager();

            $em->remove($adresse);
            $em->flush();

            $adresse = new Response('Adresse deleted successfully !');
            $adresse->headers->set('Content-Type', 'application-json');
            $adresse->headers->set('Access-Control-Allow-Origin', '*');
            $adresse->headers->set('Access-Control-Allow-Methods', 'DELETE');
            return $adresse;
        }
    }

    /**
     * @Route("/{id}/getCB", name="user_getCB", methods={"GET"})
     */
    public function getCb($id, CreditCardRepository $creditCardRepository): Response
    {
        $encoders = [new XmlEncoder(), new JsonEncoder()];
        $normalizers = [new ObjectNormalizer()];
        $serializer = new Serializer($normalizers, $encoders);

        $credit = $creditCardRepository->findByUserId($id);

        $jsonContent = $serializer->serialize($credit, 'json', [
            'circular_reference_handler' => function ($object) {
                return $object->getId();
            }
        ]);

        $ret = new Response($jsonContent);
        $ret->headers->set('Content-Type', 'application/json');
        $ret->headers->set('Access-Control-Allow-Origin', '*');
        $ret->headers->set('Access-Control-Allow-Methods', 'POST, GET, PUT, OPTIONS');
        return $ret;
    }

    /**
     * @Route("/delete/CB/{id}", name="user_deleteCB", methods={"DELETE"})
     */
    public function deleteCB(Request $request, CreditCard $creditCard, CreditCardRepository $creditCardRepository, UserRepository $userRepository): Response
    {
        $token = $request->headers->get('Authorization');
        if (in_array("ROLE_USER", $userRepository->isAuth($token)->role)){
            $cb = $creditCardRepository->find($creditCard->getId());
            $em = $this->getDoctrine()->getManager();

            $em->remove($cb);
            $em->flush();

            $cb = new Response('CreditCard deleted successfully !');
            $cb->headers->set('Content-Type', 'application-json');
            $cb->headers->set('Access-Control-Allow-Origin', '*');
            $cb->headers->set('Access-Control-Allow-Methods', 'DELETE');
            return $cb;
        }
    }

}

server/e-commerce/templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

server/e-commerce/templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

server/e-commerce/templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    <h1>Edit User</h1>

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('user_index') }}">back to list</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}

server/e-commerce/templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <h1>User index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Email</th>
                <th>Roles</th>
                <th>Password</th>
                <th>Lastname</th>
                <th>Firstname</th>
                <th>Is_online</th>
                <th>Phone</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
                <td>{{ user.password }}</td>
                <td>{{ user.lastname }}</td>
                <td>{{ user.firstname }}</td>
                <td>{{ user.isOnline ? 'Yes' : 'No' }}</td>
                <td>{{ user.phone }}</td>
                <td>
                    <a href="{{ path('user_show', {'id': user.id}) }}">show</a>
                    <a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('user_new') }}">Create new</a>
{% endblock %}

server/e-commerce/templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <h1>Create new User</h1>

    {{ include('user/_form.html.twig') }}

    <a href="{{ path('user_index') }}">back to list</a>
{% endblock %}

server/e-commerce/templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <h1>User</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ user.password }}</td>
            </tr>
            <tr>
                <th>Lastname</th>
                <td>{{ user.lastname }}</td>
            </tr>
            <tr>
                <th>Firstname</th>
                <td>{{ user.firstname }}</td>
            </tr>
            <tr>
                <th>Is_online</th>
                <td>{{ user.isOnline ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Phone</th>
                <td>{{ user.phone }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('user_index') }}">back to list</a>

    <a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}